# .circleci/config.yml 
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Compile and Run Tests
          command: mvn clean install

      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build